import images from './images';

const investments = [
  {
    title: "Oxalis",
    location: "Brooklyn, NY",
    desc: "A recognized leader in language immersion & early education, opening second school.",
    raised_current: 574920,
    raised_target: 1000000,
    security_type: "Revenue Sharing Note",
    invest_mult: 1.4,
    maturity: 48,
    min_invest: 100,
    imgUrl: images.investimg1,
    tags: ["house", "family business"]
  },
  {
    title: "Azure Café",
    location: "San Francisco, CA",
    desc: "A trendy coffee shop known for its sustainable practices, expanding to a second location.",
    raised_current: 628450,
    raised_target: 750000,
    security_type: "Convertible Note",
    invest_mult: 1.5,
    maturity: 36,
    min_invest: 250,
    imgUrl: images.investimg2,
    tags: ["food", "restaurant"]
  },
  {
    title: "GreenTech Innovations",
    location: "Austin, TX",
    desc: "Pioneering sustainable technology solutions, looking to scale production.",
    raised_current: 950000,
    raised_target: 2500000,
    security_type: "Equity",
    invest_mult: 2.0,
    maturity: 60,
    min_invest: 1000,
    imgUrl: images.investimg3,
    tags: ["business", "technology"]
  },
  {
    title: "Urban Farms Co.",
    location: "Portland, OR",
    desc: "Urban agriculture startup focusing on organic produce, aiming to expand to new cities.",
    raised_current: 450000,
    raised_target: 1000000,
    security_type: "Convertible Note",
    invest_mult: 1.3,
    maturity: 24,
    min_invest: 500,
    imgUrl: images.investimg4,
    tags: ["agriculture", "organic"]
  },
  {
    title: "Healthy Bites",
    location: "Miami, FL",
    desc: "A popular health-focused restaurant chain, planning to open 10 new locations.",
    raised_current: 1200000,
    raised_target: 3000000,
    security_type: "Preferred Stock",
    invest_mult: 1.8,
    maturity: 72,
    min_invest: 2000,
    imgUrl: images.investimg5,
    tags: ["food", "restaurant"]
  },
  {
    title: "EduTech Solutions",
    location: "Boston, MA",
    desc: "An innovative education technology company expanding its product line.",
    raised_current: 600000,
    raised_target: 1500000,
    security_type: "SAFE",
    invest_mult: 1.6,
    maturity: 48,
    min_invest: 750,
    imgUrl: images.investimg6,
    tags: ["education", "technology"]
  },
  {
    title: "BioHealth Pharmaceuticals",
    location: "San Diego, CA",
    desc: "Developing cutting-edge biotech solutions, entering phase 2 of clinical trials.",
    raised_current: 2300000,
    raised_target: 5000000,
    security_type: "Convertible Preferred Stock",
    invest_mult: 2.2,
    maturity: 60,
    min_invest: 5000,
    imgUrl: images.investimg7,
    tags: ["biotech", "healthcare"]
  },
  {
    title: "EcoFriendly Transport",
    location: "Denver, CO",
    desc: "Eco-friendly transportation startup expanding its fleet of electric vehicles.",
    raised_current: 800000,
    raised_target: 2000000,
    security_type: "Secured Note",
    invest_mult: 1.4,
    maturity: 36,
    min_invest: 1000,
    imgUrl: images.investimg8,
    tags: ["transportation", "environment"]
  },
  {
    title: "SmartHome Technologies",
    location: "Seattle, WA",
    desc: "Leading developer of smart home devices, planning to enter the European market.",
    raised_current: 1500000,
    raised_target: 4000000,
    security_type: "Revenue Sharing Note",
    invest_mult: 1.7,
    maturity: 48,
    min_invest: 1500,
    imgUrl: images.investimg9,
    tags: ["technology", "home"]
  },
  {
    title: "Oxalis",
    location: "Brooklyn, NY",
    desc: "A recognized leader in language immersion & early education, opening second school.",
    raised_current: 574920,
    raised_target: 1000000,
    security_type: "Revenue Sharing Note",
    invest_mult: 1.4,
    maturity: 48,
    min_invest: 100,
    imgUrl: images.investimg1,
    tags: ["house", "business"]
  },
  {
    title: "Azure Café",
    location: "San Francisco, CA",
    desc: "A trendy coffee shop known for its sustainable practices, expanding to a second location.",
    raised_current: 628450,
    raised_target: 750000,
    security_type: "Convertible Note",
    invest_mult: 1.5,
    maturity: 36,
    min_invest: 250,
    imgUrl: images.investimg2,
    tags: ["food", "restaurant"]
  },
  {
    title: "GreenTech Innovations",
    location: "Austin, TX",
    desc: "Pioneering sustainable technology solutions, looking to scale production.",
    raised_current: 950000,
    raised_target: 2500000,
    security_type: "Equity",
    invest_mult: 2.0,
    maturity: 60,
    min_invest: 1000,
    imgUrl: images.investimg3,
    tags: ["business", "technology"]
  },
]

export default investments